### ISSUE TITLE
Issue with npm run dev vs. npm run prod

### ISSUE THREAD

**Issue by kbefff** [ghulamabbas2/shopit#5]
Following along you Udemy course and have tried everything I can think of to get this to work. when I run "npm run dev" or "npm run prod" the global variable seems to be setting to DEVELOPMENT and only changes when I change my config.env. I started from scratch to try and fix this and have not been able to fix it. I am getting an error I will paste below, something to do with the SET NODE_ENV in the package.json... Also when I do a ctrl-c to exit the script I get an erno 130 error which looks like it's been around for a while when I googled it. Not sure if all these issues are related but would really appreciate you taking a look if you have time! I am on a mac running npm 6.14.10 and node v14.15.4

my repo is here:https://github.com/kbefff/shop-it

<img width="740" alt="Screen Shot 2021-02-08 at 1 26 50 PM" src="https://user-images.githubusercontent.com/25047389/107284349-877cf100-6a12-11eb-8e5a-1277887599f0.png">

**Comment by ghulamabbas2** [comment]
I think you are using the different terminal. Can you please mention the name of terminal because when you run the command it says **"sh: SET: Command not found**"

**Comment by kbefff** [comment]
I'm using zsh. I can change the NODE_ENV by setting it globally in my terminal but can't figure out how to automate it in my package.json

**Comment by kbefff** [comment]
I'm using iTerm2 with a zsh shell

**Comment by ghulamabbas2** [comment]
Shell script doesn't have **SET** command, just had: **set**

**Comment by kbefff** [comment]
when I use "set" instead of "SET" in the package.json script it does not actually resent my environment variable. It still uses the NODE_ENV=DEVELOPMENT in my config.env
<img width="572" alt="Screen Shot 2021-02-09 at 12 23 30 PM" src="https://user-images.githubusercontent.com/25047389/107423853-c0c86600-6ad1-11eb-8092-3494b43cb0af.png">

**Comment by ghulamabbas2** [comment]
Are you on MAC?

**Comment by kbefff** [comment]
yes

**Comment by kbefff** [comment]
I'm loving your course btw!!

**Comment by ghulamabbas2** [comment]
In that case, you don't have to use **set** and also **&**

Your scripts will look like this:

`NODE_ENV=DEVELOPMENT nodemon backend/server`
`NODE_ENV=PRODUCTON nodemon backend/server`

**Comment by ghulamabbas2** [comment]
> I'm loving your course btw!!

I'm glad to know that you like this course. Thank You for taking this course

**Comment by kbefff** [comment]
hmm still doesn't seem to be working... 


<img width="572" alt="Screen Shot 2021-02-09 at 12 23 30 PM" src="https://user-images.githubusercontent.com/25047389/107425652-16057700-6ad4-11eb-97fd-d762e6ccd3c3.png">
<img width="1090" alt="Screen Shot 2021-02-09 at 12 38 47 PM" src="https://user-images.githubusercontent.com/25047389/107425656-1736a400-6ad4-11eb-96c4-48802c839ae3.png">

**Comment by ghulamabbas2** [comment]
Remove **&** also.

**Comment by kbefff** [comment]
that worked! Thank you so much for responding quickly and clearly! I look forward to continuing this course :)

**Comment by ghulamabbas2** [comment]
Great!!!
