### ISSUE TITLE
Reciving an Error by issuing POST on Postman 

### ISSUE THREAD

**Issue by arsal-subhan** [ghulamabbas2/shopit#6]
The following error is being received on Postman after trying to post {{DOMAIN}}/api/v1/product/new and the error is displayed as Cannot POST /api/v1/product/new. Do you know what could be the cause of this error ? 

I tried several method and exactly followed your video tutorial but unfortunately it did not help me . 

<img width="1440" alt="Screenshot 2021-02-28 at 19 46 54" src="https://user-images.githubusercontent.com/66089173/109429751-c264ba00-79fd-11eb-8a60-2b643bf5d0f6.png">

**Comment by ghulamabbas2** [comment]
Have you set the routes of this controller?
And also have to set the `express.json()` ?

**Comment by arsal-subhan** [comment]
Could you kindly be a bit more elaborate on how I set the routes to this controllers and also to set the express.json  ? 

So far I was able to establish a successful local get request on postman but not the post itself and yes I did create the routes for post on  res 201 as I did for get on res 200 in the image below . I tried but unfortunately I keep coming across the same error.


<img width="1440" alt="Screenshot 2021-03-01 at 16 28 26" src="https://user-images.githubusercontent.com/66089173/109526204-9b1bf480-7ab2-11eb-9e9b-3b14f52cf4c2.png">

<img width="1440" alt="Screenshot 2021-03-01 at 16 28 39" src="https://user-images.githubusercontent.com/66089173/109526238-a2db9900-7ab2-11eb-8782-c5f3e98c6cdd.png">

<img width="1440" alt="Screenshot 2021-03-01 at 16 29 04" src="https://user-images.githubusercontent.com/66089173/109526267-a96a1080-7ab2-11eb-84d7-1c938605c9bc.png">

<img width="1440" alt="Screenshot 2021-03-01 at 17 23 20" src="https://user-images.githubusercontent.com/66089173/109526466-df0ef980-7ab2-11eb-8b82-51375cd5a11e.png">

**Comment by ghulamabbas2** [comment]
You have missed / in the post route. Refer to the below screenshot:

 
![user git](https://user-images.githubusercontent.com/60650799/109540782-c3bce200-7ae4-11eb-9cb3-8550a5248b97.png)

**Comment by arsal-subhan** [comment]
Thanks a lot it worked !!!
